// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package cnt_control_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} enable;
    struct packed {logic q;} clear;
  } cnt_control_reg2hw_control_reg_t;

  typedef struct packed {logic [31:0] q;} cnt_control_reg2hw_threshold_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } clear;
  } cnt_control_hw2reg_control_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } cnt_control_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    cnt_control_reg2hw_control_reg_t   control;    // [33:32]
    cnt_control_reg2hw_threshold_reg_t threshold;  // [31:0]
  } cnt_control_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    cnt_control_hw2reg_control_reg_t control;  // [3:2]
    cnt_control_hw2reg_status_reg_t  status;   // [1:0]
  } cnt_control_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CNT_CONTROL_CONTROL_OFFSET = 4'h0;
  parameter logic [BlockAw-1:0] CNT_CONTROL_STATUS_OFFSET = 4'h4;
  parameter logic [BlockAw-1:0] CNT_CONTROL_THRESHOLD_OFFSET = 4'h8;

  // Register index
  typedef enum int {
    CNT_CONTROL_CONTROL,
    CNT_CONTROL_STATUS,
    CNT_CONTROL_THRESHOLD
  } cnt_control_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CNT_CONTROL_PERMIT[3] = '{
      4'b0001,  // index[0] CNT_CONTROL_CONTROL
      4'b0001,  // index[1] CNT_CONTROL_STATUS
      4'b1111  // index[2] CNT_CONTROL_THRESHOLD
  };

endpackage

